### ISSUE TITLE
igraph bfs/dfs segmentation faults

### ISSUE THREAD

**Issue by ludwikbukowski** [igraph/rigraph#253]
Hi, I am just playing with `dfs`/`bfs` functions and Im trying to access vertex attributes in callback function but everytime it crashes R vm:
```
library('igraph')
g <- make_tree(10)
g<- set_vertex_attr(g, "xx", value = 10:19)
f.in <- function(graph, data, extra) {
## print(graph[data[1]]$xx) $$ I tried something like this but doesnt work
print(graph) ## even this crashes R
FALSE
}
tmp <- bfs(g, root=1, "out",callback=f.in)
```
Even printing graph structure in callback function breaks everything...

**Comment by zettsu-t** [comment]
I found a similar issue to call an igraph function in callbacks. The following code crashes in igraph 1.2.4.1.

```R
library(igraph)
f <- function(h,v,e){
  igraph::neighbors(h,1)
  FALSE
}
g <- igraph::graph_from_data_frame(data.frame(from=1,to=2))
igraph::bfs(graph=g,root=1,neimode="all",callback=f)
```

Here is my environment to run the code shown above.

```text
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Japanese_Japan.932  LC_CTYPE=Japanese_Japan.932
[3] LC_MONETARY=Japanese_Japan.932 LC_NUMERIC=C
[5] LC_TIME=Japanese_Japan.932

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] igraph_1.2.4.1

loaded via a namespace (and not attached):
[1] compiler_3.6.0  magrittr_1.5    tools_3.6.0     pkgconfig_2.0.2
```

**Comment by szhorvat** [comment]
@vtraag Still crashed in the dev version, we should investigate.

**Comment by szhorvat** [comment]
With 1.3 dev version:

```
> library(igraph)
> f <- function(h,v,e){
+     igraph::neighbors(h,1)
+     FALSE
+ }
> g <- igraph::graph_from_data_frame(data.frame(from=1,to=2))
> igraph::bfs(graph=g,root=1,neimode="all",callback=f)
```

```
Error in igraph::bfs(graph = g, root = 1, neimode = "all", callback = f) : 
  At core/core/dqueue.pmt:105 : Assertion failed: q->stor_begin != 0. This is an unexpected igraph error; please report this as a bug, along with the steps to reproduce it.
```

**Comment by ntamas** [comment]
The callbacks of the `bfs` / `dfs` functions seem to be fundamentally broken at the moment; in particular:

* returning anything that is a non-logical value crashes R (and this can happen easily if you forget to put `FALSE` at the end of the callback)
* any sort of error raised from the callback crashes R
* the vertex IDs in the named vector of the callback are 0-based, not 1-based

I'll have to look into how the callbacks are implemented to see if this is easy to fix.

**Comment by szhorvat** [comment]
BTW OP's example no longer seems to crash in dev version.

**Comment by ntamas** [comment]
`R_igraph_finalizer()` also takes care of hiding the progress bar in case it's still visible.

**Comment by ntamas** [comment]
I don't know; I'm not that familiar with the R internals either, but calling `IGRAPH_FINALLY_FREE()` multiple times should be safe. The calling-igraph-functions-from-callbacks problem should be solved with the introduction of the multi-level finally stack in the C core, so once we migrate to 0.10 in the R interface we can cross out the last remaining item from [my comment](https://github.com/igraph/rigraph/issues/253#issuecomment-1004438509).

**Comment by pchtsp** [comment]
> BTW OP's example no longer seems to crash in dev version.

```
> library('igraph')
> g <- make_tree(10)
> g<- set_vertex_attr(g, "xx", value = 10:19)
> f.in <- function(graph, data, extra) {
+     ## print(V(graph)[data[1]]$xx) $## I tried something like this but doesnt work
+     print(graph) ## even this crashes R
+     FALSE
+ }
> tmp <- bfs(g, root=1, "out",callback=f.in)
IGRAPH cb553c5 D--- 10 9 -- Tree
+ attr: name (g/c), children (g/n), mode (g/c), xx (v/n)
+ edges from cb553c5:
[1] 1-> 2 1-> 3 2-> 4 2-> 5 3-> 6 3-> 7 4-> 8 4-> 9 5->10
Error in bfs(g, root = 1, "out", callback = f.in) : 
  At core/core/dqueue.pmt:105 : Assertion failed: q->stor_begin != 0. This is an unexpected igraph error; please report this as a bug, along with the steps to reproduce it.
```

environment:
```
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] igraph_1.3.1.9013

loaded via a namespace (and not attached):
[1] compiler_4.2.0  magrittr_2.0.3  tools_4.2.0     pkgconfig_2.0.3
```

I just tried the current development version and the example still crashes for me (Ubuntu. I hope the issue can be solved soon! And thanks for the library, it's great :  )

**Comment by ntamas** [comment]
Addition: using `print(unclass(g))` inside the callback works, which points further towards the direction of `print()` (or, more precisely, `print.igraph`). Adding _another_ `print` after `print(g)` in the callback gets executed correctly, so `print()` within the callback is not returning an error, therefore I don't think that the error handler is involved; it must be something else.

**Comment by ntamas** [comment]
Okay, so it's simple and it will be solved in future versions when we switch the C core to 0.10, where we have the multi-level error stack available. The problem appears not only with `print()` but also with simpler igraph functions like `is_directed(graph)`. The source code of the R part of `is_directed(graph)` looks like this:

```
function (graph)
{
    if (!is_igraph(graph)) {
        stop("Not a graph object")
    }
    on.exit(.Call(C_R_igraph_finalizer))
    .Call(C_R_igraph_is_directed, graph)
}
```

`on.exit()` is meant to schedule a call to `C_R_igraph_finalizer` when the execution returns to the top level. However, since the callbacks are now executed in a separate R context (so we can catch errors from the callback), `C_R_igraph_finalizer` gets called when we return from the R side of the callback to the C side of the callback inside the BFS, and indeed `C_R_igraph_finalizer` frees all the data structures required for the BFS at that point as it knows nothing about the callback.

Since igraph 0.10 on the C side is still far away in the pipeline, I'll try to think about alternative solutions.

**Comment by szhorvat** [comment]
@krlmlr Fixing this is unrealistic within the timeframe we have for 2.0.0. Removing from blocker list, re-add if you disagree.

**Comment by maelle** [comment]
Current state of that reprex

``` r
library('igraph')
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
g <- make_tree(10)
f.in <- function(graph, data, extra) { print(graph); FALSE }
bfs(g, root=1, "out",callback=f.in)
#> ── <igraph> Tree ──────────────────────────────────────────────────── 5eebc46 ──
#> ℹ directed
#> ℹ 10 vertices · 9 edges
#> 
#> ── Attributes ──────────────────────────────────────────────────────────────────
#> → graph:  name <chr>, children <dbl>, mode <chr>
#> 
#> ── Edges ───────────────────────────────────────────────────────────────────────
#> [1] 1 → 2   1 → 3   2 → 4   2 → 5   3 → 6   3 → 7   4 → 8   4 → 9   5 → 10
#> Error in `bfs()`:
#> ! At vendor/cigraph/src/core/dqueue.pmt:120 : Assertion failed: q->stor_begin != NULL. This is an unexpected igraph error; please report this as a bug, along with the steps to reproduce it.
#> Please restart your R session to avoid crashes or other surprising behavior.
```

<sup>Created on 2026-08-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment]
Thanks. Let's reassess once we have vendored v1.0.x .
